# Generated by Django 5.1.4 on 2025-03-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('discord_link', models.URLField(verbose_name='Discord Davet Linki')),
                ('community_image', models.ImageField(upload_to='discord/', verbose_name='Topluluk Görseli')),
                ('member_count', models.CharField(default='1500+', max_length=50, verbose_name='Üye Sayısı')),
            ],
            options={
                'verbose_name': 'Discord Bölümü',
                'verbose_name_plural': 'Discord Bölümü',
            },
        ),
        migrations.CreateModel(
            name='DiscordFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='İkon')),
                ('text', models.CharField(max_length=50, verbose_name='Özellik')),
                ('discord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.discordsection')),
            ],
            options={
                'verbose_name': 'Discord Özelliği',
                'verbose_name_plural': 'Discord Özellikleri',
            },
        ),
    ]
