# Generated by Django 5.1.4 on 2025-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordsection',
            name='member_count',
        ),
    ]
