# Generated by Django 5.1.4 on 2025-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_discordsection_member_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Örn: fas fa-rocket', max_length=50, verbose_name='İkon')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('order', models.PositiveIntegerField(verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ['order'],
            },
        ),
    ]
