# Generated by Django 5.1.4 on 2025-03-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='about/', verbose_name='Profil Fotoğrafı')),
                ('experience_years', models.CharField(help_text='Örn: 3+', max_length=10, verbose_name='Deneyim Yılı')),
                ('title', models.CharField(default='Ben Kimim?', max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Ana Açıklama')),
            ],
            options={
                'verbose_name': 'Hakkımda Bölümü',
                'verbose_name_plural': 'Hakkımda Bölümü',
            },
        ),
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Örn: fas fa-briefcase', max_length=50, verbose_name='İkon')),
                ('description', models.TextField(verbose_name='Detay Açıklaması')),
                ('order', models.PositiveIntegerField(verbose_name='Sıralama')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.aboutsection')),
            ],
            options={
                'verbose_name': 'Hakkımda Detay',
                'verbose_name_plural': 'Hakkımda Detayları',
                'ordering': ['order'],
            },
        ),
    ]
