# Generated by Django 5.1.4 on 2025-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Eğitim Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('thumbnail', models.ImageField(upload_to='courses/', verbose_name='Eğitim Görseli')),
                ('url', models.URLField(verbose_name='Eğitim Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_active', models.BooleanField(verbose_name='Aktif mi?')),
                ('order', models.PositiveIntegerField(verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
