# Generated by Django 5.1.4 on 2025-03-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_blogdocument_bloglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdocument',
            name='file_size',
        ),
    ]
